### ISSUE TITLE
Nimble init should allow "proprietary"

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/nimble#507]
While it makes sense to require an open source license for packages published on the central package repository, private projects may not have a license, while still benefit from Nimble for building, dependency management, tasks and so on

**Comment by dom96** [comment]
You can specify "Proprietary" as a license for those projects.

**Comment by andreaferretti** [comment]
Nimble init rejects it

**Comment by BarelyMalicious** [comment]
Currently, nimble init does not allow skipping Package Licence prompt
```
    Prompt: Package License? [MIT/BSD2/GPLv3/LGPLv3/Apache2]
    Answer:
    Answer:
    Answer:
    Answer:
    Answer:
    Answer:
```

Maybe add proprietary as default if the user presses enter.
And also maybe give user the option to input any licence he wants to add because the current list (MIT/BSD2/GPLv3/LGPLv3/Apache2) is too small.
